version: "3.3"
services:
  app:
    build: .
    working_dir: /app/
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    command: python -m gunicorn -c asgi.py test:app
    environment:
      - TZ=Europe/Moscow
